package policyfile

import (
	"archive/tar"
	"compress/gzip"
	"context"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"

	cinc "github.com/cinc-project/cinc-api"
)

// ExportResult describes a completed export.
type ExportResult struct {
	Dir     string `json:"dir"`
	Archive string `json:"archive,omitempty"`
	Policy  string `json:"policy"`
}

// Export assembles a standalone, Chef-compatible bundle for an air-gapped
// `cinc-client -z` run: every pinned cookbook under
// cookbooks/<name>-<dotted_decimal_identifier>/, the lock under both
// policies/<name>-<revision>.json and Policyfile.lock.json, and a generated
// client.rb selecting the policy in local mode. With archive, the directory is
// also written as <dir>.tar.gz. Cookbooks are sourced through the fetcher
// (cache or fresh fetch).
func Export(ctx context.Context, fetcher *Fetcher, lock *cinc.PolicyRevision, lockJSON []byte, destDir string, archive bool) (ExportResult, error) {
	if err := os.MkdirAll(filepath.Join(destDir, "cookbooks"), extractDirMode); err != nil {
		return ExportResult{}, err
	}
	if err := os.MkdirAll(filepath.Join(destDir, "policies"), extractDirMode); err != nil {
		return ExportResult{}, err
	}

	for _, name := range sortedLockNames(lock.CookbookLocks) {
		cl := lock.CookbookLocks[name]
		src, err := fetcher.EnsureCookbook(ctx, name, cl)
		if err != nil {
			return ExportResult{}, err
		}
		ddi := cl.DottedDecimalIdentifier
		if ddi == "" {
			ddi = cl.Identifier
		}
		// name and ddi come from the (untrusted) lock; keep them from escaping
		// the export directory.
		dst, err := safeJoin(destDir, "cookbooks", name+"-"+ddi)
		if err != nil {
			return ExportResult{}, fmt.Errorf("policyfile: cookbook %q: %w", name, err)
		}
		if err := copyTree(src, dst); err != nil {
			return ExportResult{}, fmt.Errorf("policyfile: copy cookbook %q: %w", name, err)
		}
	}

	revision := lock.RevisionID
	if revision == "" {
		revision = "revision"
	}
	policyFile, err := safeJoin(destDir, "policies", lock.Name+"-"+revision+".json")
	if err != nil {
		return ExportResult{}, fmt.Errorf("policyfile: %w", err)
	}
	if err := os.WriteFile(policyFile, lockJSON, extractFileMode); err != nil {
		return ExportResult{}, err
	}
	if err := os.WriteFile(filepath.Join(destDir, "Policyfile.lock.json"), lockJSON, extractFileMode); err != nil {
		return ExportResult{}, err
	}
	if err := os.WriteFile(filepath.Join(destDir, "client.rb"), []byte(clientRB(lock.Name)), extractFileMode); err != nil {
		return ExportResult{}, err
	}

	result := ExportResult{Dir: destDir, Policy: lock.Name}
	if archive {
		archivePath := destDir + ".tar.gz"
		if err := tarGzDir(destDir, archivePath); err != nil {
			return ExportResult{}, err
		}
		result.Archive = archivePath
	}
	return result, nil
}

// clientRB is the generated local-mode client configuration that selects the
// exported policy, suitable for `cinc-client -z`.
func clientRB(policyName string) string {
	return fmt.Sprintf(`# Generated by `+"`cinc policy export`"+`.
use_policyfile true
policy_name %q
policy_group "local"
`, policyName)
}

func sortedLockNames(m map[string]cinc.CookbookLock) []string {
	names := make([]string, 0, len(m))
	for k := range m {
		names = append(names, k)
	}
	sort.Strings(names)
	return names
}

// copyTree recursively copies the directory src into dst, clamping file modes
// and skipping any .git directory.
//
// Only regular files are copied. filepath.Walk reports symlinks via Lstat, so
// without an explicit check a link would be opened, following it and writing
// the contents of whatever it points at into the destination: a cookbook
// carrying "files/creds -> ~/.ssh/id_rsa" would put that key in an export
// bundle bound for the server. Skipping them also keeps a dangling link, which
// cookbooks legitimately carry, from failing the whole copy. This matches how
// cli/cookbook's archiveEntries builds an upload.
func copyTree(src, dst string) error {
	return filepath.Walk(src, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() && info.Name() == ".git" {
			return filepath.SkipDir
		}
		rel, err := filepath.Rel(src, path)
		if err != nil {
			return err
		}
		target := filepath.Join(dst, rel)
		if info.IsDir() {
			return os.MkdirAll(target, extractDirMode)
		}
		if !info.Mode().IsRegular() {
			return nil
		}
		if err := os.MkdirAll(filepath.Dir(target), extractDirMode); err != nil {
			return err
		}
		in, err := os.Open(path)
		if err != nil {
			return err
		}
		defer func() { _ = in.Close() }() // read handle
		// Clamp to a safe mode rather than trusting the source file's bits.
		out, err := os.OpenFile(target, os.O_CREATE|os.O_TRUNC|os.O_WRONLY, extractFileMode)
		if err != nil {
			return err
		}
		if _, err := io.Copy(out, in); err != nil {
			_ = out.Close() // already returning an error
			return err
		}
		return out.Close()
	})
}

// tarGzDir writes dir as a gzip-compressed tarball at archivePath, with entries
// rooted at the directory's base name.
func tarGzDir(dir, archivePath string) (err error) {
	f, err := os.Create(archivePath)
	if err != nil {
		return err
	}
	gz := gzip.NewWriter(f)
	tw := tar.NewWriter(gz)
	// The tar trailer and the gzip footer are written by Close, so a failure
	// there means a truncated archive. Closing innermost first and keeping the
	// first error is what makes that surface instead of being reported as a
	// successful export.
	defer func() {
		for _, c := range []io.Closer{tw, gz, f} {
			if cerr := c.Close(); err == nil {
				err = cerr
			}
		}
	}()

	root := filepath.Base(dir)
	return filepath.Walk(dir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(dir, path)
		if err != nil {
			return err
		}
		if rel == "." {
			return nil
		}
		hdr, err := tar.FileInfoHeader(info, "")
		if err != nil {
			return err
		}
		hdr.Name = filepath.ToSlash(filepath.Join(root, rel))
		if err := tw.WriteHeader(hdr); err != nil {
			return err
		}
		if info.IsDir() {
			return nil
		}
		in, err := os.Open(path)
		if err != nil {
			return err
		}
		defer func() { _ = in.Close() }() // read handle
		_, err = io.Copy(tw, in)
		return err
	})
}
