package suite

// aclFamily is not ported from test/acceptance yet.
var aclFamily = family{
	pending: []string{
		"client acl grant",
		"client acl revoke",
		"client acl show",
		"cookbook acl grant",
		"cookbook acl revoke",
		"cookbook acl show",
		"databag acl grant",
		"databag acl revoke",
		"databag acl show",
		"environment acl grant",
		"environment acl revoke",
		"environment acl show",
		"group acl grant",
		"group acl revoke",
		"group acl show",
		"node acl grant",
		"node acl revoke",
		"node acl show",
		"org acl grant",
		"org acl revoke",
		"org acl show",
		"policy acl grant",
		"policy acl revoke",
		"policy acl show",
		"policy-group acl grant",
		"policy-group acl revoke",
		"policy-group acl show",
		"role acl grant",
		"role acl revoke",
		"role acl show",
		"user acl grant",
		"user acl revoke",
		"user acl show",
	},
}
